### ISSUE TITLE
lv_micropython　のバージョンが変わりインストールできない

### ISSUE THREAD

**Issue by mnltake** [mnltake/lvglnavi#2]
lv_micropython　のバージョンが変わりインストールできないとの報告

`install.sh`

echo 8/$n #lvgl micropython
cd ~
sudo apt install build-essential libreadline-dev libffi-dev git pkg-config libsdl2-2.0-0 libsdl2-dev parallel wmctrl -y
git clone --recurse-submodules https://github.com/lvgl/lv_micropython.git
cd ~/lvglnavi/
git switch release/v7

で元のバージョンに戻せないか？（未検証）

**Comment by mnltake** [comment]
動作確認できてるlv_micropythonバージョンはこれです
https://github.com/lvgl/lv_micropython/tree/d8a68915baa797d02b24f12c2112ff02ac201681

**Comment by GalleyLa** [comment]
バージョンが分かったので、git checkout してmakeまで完了しました。
checkoutしただけだと--recurse-submodules したサブモジュールはcheckoutされ無い様でしたので以下の操作をおこなっております。
install.sh修正頂いておりましたが、cdの位置を修正しています。
46 ~cd ~/lv_micropython
47 git checkout d8a68915baa797d02b24f12c2112ff02ac201681
48 git submodule update --init --recursive

cd ~/lvglnavi/

F9Pの設定やRaspberry piの接続など完了し、実際に動作出来たら結果をアップします。

ひとまず有難うございました。
